name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup database
        run: |
          cd cypress/cypress-realworld-app
          yarn install
          yarn db:seed

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          working-directory: cypress/cypress-realworld-app
          wait-on: 'http://localhost:3000'
        env:
          HUSKY: 0
