name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          build: cd cypress/cypress-realworld-app && yarn db:seed
          start: cd cypress/cypress-realworld-app && yarn dev
          wait-on: 'http://localhost:3000'
        env:
          HUSKY: 0
