name: Cypress Tests
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Link .git for postinstall
        run: ln -s ../../.git .git
        working-directory: ./cypress/cypress-realworld-app

      - name: Install dependencies
        run: yarn install --ignore-scripts
        working-directory: ./cypress/cypress-realworld-app

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./cypress/cypress-realworld-app
          start: yarn dev
          wait-on: 'http://localhost:3000,http://localhost:3002'
          wait-on-timeout: 180
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
